/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bsf.conn;

/**
 *
 * @author rajat_000
 */
import javax.swing.*;
import java.sql.*;
<<<<<<< HEAD
import bsf.main.*;
public class LoginPage extends javax.swing.JFrame {
private Connection con = null;
PreparedStatement ps = null;
ResultSet rs = null;
=======
import bsf.info.*;
public class LoginPage extends javax.swing.JFrame {
Connection con = null;
>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35

public LoginPage() {
        initComponents();
        con = JavaConnector.connectionDb();
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBLogin = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
<<<<<<< HEAD
        jBReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
=======

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setText("Password");

        jLabel1.setText("UserName :");

        jBLogin.setText("Login");
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        jBLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBLoginKeyPressed(evt);
            }
        });

        jBReset.setText("Reset");
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });
        jBReset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBResetKeyPressed(evt);
            }
        });
=======
>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPassword)
                    .addComponent(jUserName))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jBLogin)
                .addGap(18, 18, 18)
                .addComponent(jBReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(jBLogin)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPassword)
                            .addComponent(jUserName))))
                .addContainerGap())
>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
<<<<<<< HEAD
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLogin)
                    .addComponent(jBReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("images.jpg"));

=======
                .addComponent(jBLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
=======
                .addContainerGap(168, Short.MAX_VALUE)
>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
=======
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
        String sql = "select * from admins where Name=? and Password=? ";
        try
        {
            ps = con.prepareStatement(sql);
            ps.setString(1, jUserName.getText());
            ps.setString(2, jPassword.getText());
            rs= ps.executeQuery();
            
            if (rs.next())
                {
                    JOptionPane.showMessageDialog(null, "UserName And Password Is Correct");
                    
                    new Home().setVisible(true);
                    this.setVisible(false);
                }
            else
            {
                JOptionPane.showMessageDialog(null, "UserName And Password Is Not Correct");
            }
            ps.close();
            rs.close();
        }
        catch(Exception ex)
        {
                        JOptionPane.showMessageDialog(null, "UserName And Password Is Not Correct");
        }
            
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jBLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBLoginKeyPressed
        // TODO add your handling code here:
         String sql = "select * from admins where Name=? and Password=? ";
        try
        {
            ps = con.prepareStatement(sql);
            ps.setString(1, jUserName.getText());
            ps.setString(2, jPassword.getText());
            rs= ps.executeQuery();
            
            if (rs.next())
                {
                    JOptionPane.showMessageDialog(null, "UserName And Password Is Correct");
                    
                    new Home().setVisible(true);
                    this.setVisible(false);
                }
            else
            {
                JOptionPane.showMessageDialog(null, "UserName And Password Is Not Correct");
            }
            ps.close();
            rs.close();
        }
        catch(Exception ex)
        {
                        JOptionPane.showMessageDialog(null, "UserName And Password Is Not Correct");
        }
       
    }//GEN-LAST:event_jBLoginKeyPressed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed
        // TODO add your handling code here:
        jUserName.setText(null);
        jPassword.setText(null);
    }//GEN-LAST:event_jBResetActionPerformed

    private void jBResetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBResetKeyPressed
        // TODO add your handling code here:
        jUserName.setText(null);
        jPassword.setText(null);
    
    }//GEN-LAST:event_jBResetKeyPressed

=======
        if (jUserName.getText().equals("Vinod") && jPassword.getText().equals("root"))
                {
                    JOptionPane.showMessageDialog(null, "UserName And Password Is Correct");
                    PersonalInformation pi = new PersonalInformation();
                    pi.setVisible(true);
                }
        else
        {
                        JOptionPane.showMessageDialog(null, "UserName And Password Is Not Correct");
        }
    }//GEN-LAST:event_jBLoginActionPerformed

>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLogin;
<<<<<<< HEAD
    private javax.swing.JButton jBReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
=======
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
>>>>>>> a8fee7df1a23f0ccd90e67e18f60cd92053cbc35
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUserName;
    // End of variables declaration//GEN-END:variables
}
