/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bsf.main;

import bsf.conn.*;
import bsf.info.*;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author win8
 */
public class info extends javax.swing.JFrame {

    /**
     * Creates new form info
     */
    public info() {
        initComponents();
        DBMS.updateTable(personalInfo, "PersonalInformation");
        DBMS.updateTable(runningDetails, "Running");
        DBMS.updateTable(leaveDetails, "LeaveDetails");
        DBMS.updateTable(familyInfo, "FamilyInformation");
        DBMS.updateTable(courseDetails, "CourseDetails");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        personalInfo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        runningDetails = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        leaveDetails = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        familyInfo = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        courseDetails = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMFille = new javax.swing.JMenu();
        jMExportToPdf = new javax.swing.JMenuItem();
        jMExportToExcess = new javax.swing.JMenuItem();
        jMPrint = new javax.swing.JMenuItem();
        jMClose = new javax.swing.JMenuItem();
        jMEdit = new javax.swing.JMenu();
        jMUpdate = new javax.swing.JMenuItem();
        jMDelete = new javax.swing.JMenuItem();
        jMAdd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personalInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(personalInfo);

        jTabbedPane1.addTab("Personal Information", jScrollPane1);

        runningDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(runningDetails);

        jTabbedPane1.addTab("running Details", jScrollPane2);

        leaveDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(leaveDetails);

        jTabbedPane1.addTab("Leave Details", jScrollPane3);

        familyInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(familyInfo);

        jTabbedPane1.addTab("Family Info", jScrollPane4);

        courseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(courseDetails);

        jTabbedPane1.addTab("Course Details", jScrollPane5);

        jMFille.setText("File");

        jMExportToPdf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMExportToPdf.setText("Export To Pdf");
        jMExportToPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExportToPdfActionPerformed(evt);
            }
        });
        jMFille.add(jMExportToPdf);

        jMExportToExcess.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMExportToExcess.setText("Export To Excess");
        jMExportToExcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExportToExcessActionPerformed(evt);
            }
        });
        jMFille.add(jMExportToExcess);

        jMPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMPrint.setText("Print");
        jMPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPrintActionPerformed(evt);
            }
        });
        jMFille.add(jMPrint);

        jMClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMClose.setText("close");
        jMClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCloseActionPerformed(evt);
            }
        });
        jMFille.add(jMClose);

        jMenuBar1.add(jMFille);

        jMEdit.setText("Edit");

        jMUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMUpdate.setText("Edit");
        jMUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUpdateActionPerformed(evt);
            }
        });
        jMEdit.add(jMUpdate);

        jMDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        jMDelete.setText("Delete");
        jMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDeleteActionPerformed(evt);
            }
        });
        jMEdit.add(jMDelete);

        jMAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMAdd.setText("Add");
        jMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAddActionPerformed(evt);
            }
        });
        jMEdit.add(jMAdd);

        jMenuBar1.add(jMEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMExportToPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExportToPdfActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setDialogTitle("Save");
        if ( fileChooser.showOpenDialog(jMExportToPdf) == JFileChooser.APPROVE_OPTION)
        {
        }
         String str = fileChooser.getSelectedFile().getAbsolutePath();
         str = str.replace("\\", "\\\\");
         DBMS.pdfConvertor(personalInfo,str+"\\BSF.pdf");
         JOptionPane.showMessageDialog(null,"File Saved");
    }//GEN-LAST:event_jMExportToPdfActionPerformed

    private void jMExportToExcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExportToExcessActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setDialogTitle("Save");
        if ( fileChooser.showOpenDialog(jMExportToExcess) == JFileChooser.APPROVE_OPTION)
        {
        }
         String str = fileChooser.getSelectedFile().getAbsolutePath();
         str = str.replace("\\", "\\\\");
         DBMS.excessConvertor("Personal Information","Leave Information","Running Information","Family Information","Course Information",str+"\\BSF.xls");
         JOptionPane.showMessageDialog(null,"File Saved");
    }//GEN-LAST:event_jMExportToExcessActionPerformed

    private void jMPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPrintActionPerformed
        // TODO add your handling code here:
        DBMS.printTable(personalInfo, runningDetails, leaveDetails, familyInfo, courseDetails);
    }//GEN-LAST:event_jMPrintActionPerformed

    private void jMUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUpdateActionPerformed
        // TODO add your handling code here:
        try{
        int reg = Integer.parseInt(JOptionPane.showInputDialog("Enter Regimental No :"));
        
        PersonalInformation.jTRegimentalNo.setText(""+reg);
        PersonalInformation.jOperation.setText("update");
       
        new PersonalInformation().setVisible(true);
        //DBMS.update();
        
        this.setVisible(false);
        }
        catch(Exception exception)
        {
            JOptionPane.showMessageDialog(null, "Please Enter Numeric Digits");
        }
    }//GEN-LAST:event_jMUpdateActionPerformed

    private void jMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDeleteActionPerformed
        // TODO add your handling code here:
        int reg = Integer.parseInt(JOptionPane.showInputDialog("Enter Regimental No :"));
        try{  
             if(JOptionPane.showConfirmDialog(null,"Are you sure ?","Delete",JOptionPane.YES_NO_OPTION )==0)
            {
                DBMS.deleteRecord(reg, "PersonalInformation");
                DBMS.deleteRecord(reg, "Running");
                DBMS.deleteRecord(reg, "LeaveDetails");
                DBMS.deleteRecord(reg, "FamilyInformation");
                DBMS.deleteRecord(reg, "CourseDetails");
                DBMS.updateTable(personalInfo, "PersonalInformation");
                DBMS.updateTable(runningDetails, "Running");
                DBMS.updateTable(leaveDetails, "LeaveDetails");
                DBMS.updateTable(familyInfo, "FamilyInformation");
                DBMS.updateTable(courseDetails, "CourseDetails");
                
            }
        }
        catch(Exception exception)
        {
            JOptionPane.showMessageDialog(null, "Please Enter Numeric Digits");
        }
        
    }//GEN-LAST:event_jMDeleteActionPerformed

    private void jMCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCloseActionPerformed
        // [TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMCloseActionPerformed

    private void jMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAddActionPerformed
        // TODO add your handling code here:
        try{
           
        int reg = Integer.parseInt(JOptionPane.showInputDialog("Enter Regimental No :"));
      
        PersonalInformation.jOperation.setText("add");
      
        new PersonalInformation().setVisible(true);
        
        PersonalInformation.jTRegimentalNo.setText(""+reg);
       
        this.setVisible(false);
        }
        catch(Exception exception)
        {
            JOptionPane.showMessageDialog(null, "Please Enter Numeric Digits");
        }
    }//GEN-LAST:event_jMAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable courseDetails;
    public static javax.swing.JTable familyInfo;
    private javax.swing.JMenuItem jMAdd;
    private javax.swing.JMenuItem jMClose;
    private javax.swing.JMenuItem jMDelete;
    private javax.swing.JMenu jMEdit;
    private javax.swing.JMenuItem jMExportToExcess;
    private javax.swing.JMenuItem jMExportToPdf;
    private javax.swing.JMenu jMFille;
    private javax.swing.JMenuItem jMPrint;
    private javax.swing.JMenuItem jMUpdate;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable leaveDetails;
    public static javax.swing.JTable personalInfo;
    public static javax.swing.JTable runningDetails;
    // End of variables declaration//GEN-END:variables
}
